<?php

/**
 * Implements hook_block_info().
*/
function lastupdate_block_info() {
    $blocks['lastupdateblock'] = array(
        'info' => t('Last Update Block'),
        'cache' => DRUPAL_NO_CACHE,       
    );
    return $blocks;
}

/**
* Implements hook_block_view().
*/
function lastupdate_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'lastupdateblock':
            $block['subject'] = t('Last modified date: ');
            $block['content'] = lastupdate_last_updated();
            break;
    }
    return $block;
}

function lastupdate_last_updated() {
    if(variable_get('lastupdate_lastupdate_type')== TRUE){        
        $date = variable_get('lastupdate_lastupdate_date');        
        $date = $date['day']."-".$date['month']."-".$date['year'];
        $timestamp = strtotime($date);        
        $last_updated = format_date($timestamp);
        
    }else{
    $last_updated = db_select('node', 'n')
            ->fields('n', array('changed'))
            ->condition('status', 0, '>') // only published nodes count
            ->orderBy('changed', 'DESC')
            ->range(0, 1)
            ->execute()
            ->fetchField();
    
    $last_updated = format_date($last_updated);
    }
    
    return $last_updated;
}
/**
* Implements hook_block_configure().
*/
function lastupdate_block_configure($delta = '') {
    $form = array();
    switch ($delta) {
        case 'lastupdateblock':
            $form['lastupdate_type'] = array(
                '#type' => 'checkbox',
                '#title' => 'check for input a date',
                '#default_value' => variable_get('lastupdate_lastupdate_type', FALSE),
            );
            $form['lastupdate_date'] = array(
                '#type' => 'date',
                '#title' => 'Select a date',
                '#default_value' => variable_get('lastupdate_lastupdate_date', 0),
                '#states' => array('visible' => array(
                        ':input[name="lastupdate_type"]' => array('checked' => TRUE),)),
            );
            break;
    }
    return $form;
}

/**
* Implements hook_block_save().
*/
function lastupdate_block_save($delta = '', $edit = array()) {
    switch ($delta) {
        case 'lastupdateblock':
            variable_set('lastupdate_lastupdate_type', $edit['lastupdate_type']);
            variable_set('lastupdate_lastupdate_date', $edit['lastupdate_date']);
            break;        
    }
}